apiVersion: v1
kind: Service
metadata:
  name: {{DEPLOYMENT_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{DEPLOYMENT_NAME}}
    version: {{VERSION}}
    managed-by: cloudeefly
    mcp-server: "true"
  annotations:
    cloudeefly.io/deployment-id: "{{DEPLOYMENT_ID}}"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  selector:
    app: {{DEPLOYMENT_NAME}}
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours for long-running SSE connections
